### ISSUE TITLE
How to get calibration result?

### ISSUE THREAD

**Issue by LuyaooChen** [VCL3D/StructureNet#5]
I run inference.py with example data, and I got some label_pred.png image.
How to get calibration result (intrinsics and extrinsics matrix)?
Thanks.

**Comment by LuyaooChen** [comment]
Do I have to use 'Volumetric Capture' ? But I don't have those hardware now.

**Comment by vladsterz** [comment]
Hello @LuyaooChen ,
First of all, this network, as well as the whole calibration procedure, do not estimate camera intrinsic parameters. 
This repository currently covers the correspondence establishment (calibration structure pose) part for a calibration procedure.
If you want to calibrate some arbitrary views, you can achieve it using Volumetric Capture. To do so you have to
- create a device_repository.json that contains the intrinsic camera parameters for each view and place it in the correct directory (check [here](https://vcl3d.github.io/VolumetricCapture/docs/volcap/)
- place your depthmap views in a folder you will create under "volcap/Data/Calibrations/" named as "$device_name$_Depth.pgm"
- Calibrate using volumetric capture software

**Comment by LuyaooChen** [comment]
Thank you! I will try it.

**Comment by SergeiSamuilov** [comment]
Hello @vladsterz 

Could you please share some of the source code for transforming StructureNet output into calibration data?

**Comment by vladsterz** [comment]
Hello @SergeiSamuilov  and @LuyaooChen ,
you can use the newly added "calibration.py" file in order to compute extrinsics and calibrate data.
I believe that the code is self-explanatory, so have fun :)

**Comment by FilipeLopesPires** [comment]
> Hello @SergeiSamuilov and @LuyaooChen ,
> you can use the newly added "calibration.py" file in order to compute extrinsics and calibrate data.
> I believe that the code is self-explanatory, so have fun :)

So calibration.py produces the transformation matrices for the external calibration of a setup of multiple Azure Kinects?

**Comment by vladsterz** [comment]
Yes @FilipePires98 , as well as the aligned pointclouds
