### ISSUE TITLE
Patch Failure "Assertion failed: hunk, file patch.c"

### ISSUE THREAD

**Issue by FilipeLopesPires** [VCL3D/StructureNet#6]
Hello,

I have created an anaconda environment called structurenet for this project. After installing pytorch, cuda, tinyobjloader and the remaining requirements, I moved on to installing the patch for disabling multisampling in pyrender.
However, after downloading UnixUtils and adding the executable to path, executing the "patch.exe -u <path_to renderer.py> pyrender_patch/renderer.diff" and remaining patches, the following error is raised:
> Assertion failed: hunk, file patch.c, line 321 

I have tried installing other patch.exe versions such as [this one](http://gnuwin32.sourceforge.net/packages/patch.htm), but the same error occurs (with a different line number)...

Do you recommend any approach to solve this?
Thank you for your time.

P.S.
I am using:
- Windows 10
- conda 4.10.1
- pytorch 1.2.0
- torchvision 0.4.0
- cudatoolkit 10.0

**Comment by alexd314** [comment]
Hello,

I've never run into this issue. Have you tried solutions based on line-endings, as reported in:
https://sourceforge.net/p/gnuwin32/discussion/general/thread/59954e91/
or
https://stackoverflow.com/questions/23891281/assertion-failed-when-using-patch-exe-of-git-for-windows/41120286
?

I'd first try the Notepad++ solution suggested as a second answer to the stackoverflow link above.
I'd suggest to try this first and then please report back to us if this actually worked or not.

**Comment by FilipeLopesPires** [comment]
Hello Alex,

Thank you for your quick reply. 
I will look into your suggestions and provide feedback as soon as possible.

**Comment by FilipeLopesPires** [comment]
Adding the option --binary to patch.exe seems to have solved the issue.
Thank you for providing good suggestions.
