### ISSUE TITLE
Runtime Error "IndexError: list index out of range"

### ISSUE THREAD

**Issue by FilipeLopesPires** [VCL3D/StructureNet#7]
Hello,

I tried executing inference.py with the pre-trained model you provide:
> python inference.py --input_path <path_to_repo>\example --output_path <path_to_output_dir>\output --saved_params_path <path_to_model>\model_e6.pth.tar --scale 0.001 

Scale was set to 0.001 as mentioned by @vladsterz [here](https://github.com/VCL3D/StructureNet/issues/3#issuecomment-724667979). 
But an error is raised:
> <path_to_repo>\src\dataset\rendering\transformations.py:1926: UserWarning: No module named 'src.dataset.rendering._transformations' 
> warnings.warn(str(err))
> Loading previously saved model from <path_to_model>\model_e6.pth.tar
> Loaded model name: full_mask_max                                                                                                                                                              > Traceback (most recent call last):                                                                                                                                                              > File "inference.py", line 175, in <module> 
> inference(args, device)
> File "inference.py", line 112, in inference                                                                                                                                                     > dsiterator = depthmap_dataset.DepthmapDataset(datasetparams)
> File "<path_to_repo>\src\dataset\depthmap_dataset.py", line 22, in __init__
> self._get_filelist()
> File "<path_to_repo>\src\dataset\depthmap_dataset.py", line 30, in _get_filelist
> self._filepaths.sort(key = lambda x: int(x.split("\\")[-1].split(".")[0].split("_")[2]))
> File "<path_to_repo>\src\dataset\depthmap_dataset.py", line 30, in <lambda>
> self._filepaths.sort(key = lambda x: int(x.split("\\")[-1].split(".")[0].split("_")[2]))
> IndexError: list index out of range 

Could you shed some light into what I am doing wrong?

**Comment by vladsterz** [comment]
Hello @FilipePires98 ,
is  _<path_to_repo>\example_ a real path?
<path_to_repo> is a placeholder which you change to the real directory where the repository is saved (such as C:/Users/filipe/Desktop/StructureNet")

**Comment by FilipeLopesPires** [comment]
Hello,

Thank you for your quick reply.
I have replaced the real directory path with <path_to_repo> for reading purposes.

**Comment by FilipeLopesPires** [comment]
I previously submitted an issue here regarding patch.exe failure. In the mean time that problem was solved, but this one remains.
Any suggestions on what might be causing the "IndexError: list index out of range"?

**Comment by vladsterz** [comment]
Hello @FilipePires98 ,
how are your depthmaps named?

**Comment by alexd314** [comment]
I am closing this as inactive.
